"""Candidate Observation construction for imported Twin semantic objects.

This module adapts read-only candidate Twin objects into the implemented
Enterprise Observation pipeline shape.  It does not persist, promote or create a
new canonical Observation model; it supplies deterministic Observation-compatible
statements for the existing candidate runtime and diagnostics.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any
import hashlib

from .semantic_twin import SemanticObject, executive_record_view_model

OBSERVATION_PROFILE_VERSION = "imported-twin-observation-profile-v1"
OBSERVATION_BUILDER_NAME = "ImportedTwinSemanticObservationBuilder"

SUPPORTED_OBJECT_FAMILIES: dict[str, tuple[str, ...]] = {
    "Industry Overview": ("industry", "industry_twin", "industry_overview", "subsector", "value_chain", "economic_pool"),
    "Enterprise Dossier": ("enterprise", "enterprise_twin", "enterprise_dossier", "entity"),
    "Market Participant": ("market_participant", "market_participant_twin"),
    "Transformation Programme": ("transformation_programme",),
    "Opportunity": ("opportunity", "opportunity_hypothesis", "ranked_opportunity", "opportunity_twin"),
    "Reinvention Assessment": ("ai_reinvention_assessment",),
}

_KIND_TO_FAMILY = {kind: family for family, kinds in SUPPORTED_OBJECT_FAMILIES.items() for kind in kinds}

@dataclass(frozen=True)
class CandidateObservation:
    observation_id: str
    builder: str
    profile: str
    originating_object: str
    originating_fields: tuple[str, ...]
    statement: str
    evidence_refs: tuple[str, ...]
    confidence: str
    subject: str
    observation_type: str
    observed_at: str
    owner_assessment_state: str = "assessment_pending_governance"
    persistence_state: str = "candidate_read_projection_only"


def observation_family(kind: str) -> str:
    return _KIND_TO_FAMILY.get(kind, "Unsupported")


def build_candidate_observation(obj: SemanticObject, *, observed_at: str | None = None) -> tuple[CandidateObservation | None, str, str]:
    """Return an Observation-compatible candidate projection or an exact skip reason.

    The Programme path already succeeds because programmes carry an explicit
    semantic statement.  The same builder also derives a statement from the
    canonical executive view-model fields for supported factual object families.
    """
    family = observation_family(obj.kind)
    if family == "Unsupported":
        return None, "unsupported_object_family", "Object kind is not registered in the imported Twin Observation profile."
    if obj.validation_status and obj.validation_status not in {"accepted", ""}:
        return None, "candidate_state_suppressed", obj.residual_reason or "Candidate validation status is not accepted."
    if not obj.subject or obj.subject == "Twin scope":
        return None, "missing_subject", "Observation requires a canonical subject."
    statement, fields = _statement_and_fields(obj)
    if not statement:
        return None, "missing_statement", "No statement available from semantic statement or registered factual fields."
    now = observed_at or datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    oid = _observation_id(obj, statement, fields)
    return CandidateObservation(oid, OBSERVATION_BUILDER_NAME, OBSERVATION_PROFILE_VERSION,
        obj.original_id or obj.record_id, fields, statement, obj.evidence_refs, obj.confidence,
        obj.subject, _observation_type(obj), now), "observation_generated", "Generated by imported Twin semantic Observation builder."


def _statement_and_fields(obj: SemanticObject) -> tuple[str, tuple[str, ...]]:
    if obj.statement and not obj.statement.lstrip().startswith("{"):
        return obj.statement, ("statement",)
    view = executive_record_view_model(obj)
    if not view.fields:
        return (obj.statement if obj.statement and obj.statement.lstrip().startswith("{") is False else ""), ("statement",) if obj.statement else ()
    label, value = view.fields[0]
    return f"{obj.subject} — {label}: {_render_value(value)}", (label,)


def _render_value(value: Any) -> str:
    if isinstance(value, dict):
        return "; ".join(f"{str(k).replace('_',' ')}: {_render_value(v)}" for k, v in value.items() if v not in (None, "", [], {}))
    if isinstance(value, (list, tuple)):
        return "; ".join(_render_value(v) for v in value if v not in (None, "", [], {}))
    return str(value)


def _observation_id(obj: SemanticObject, statement: str, fields: tuple[str, ...]) -> str:
    seed = "|".join((obj.record_id, obj.original_id, obj.kind, statement, ",".join(fields)))
    return "OBS-CAND-" + hashlib.sha256(seed.encode()).hexdigest()[:16].upper()


def _observation_type(obj: SemanticObject) -> str:
    if obj.kind == "transformation_programme": return "programme_candidate_fact"
    if "opportun" in obj.kind: return "opportunity_candidate_fact"
    if obj.kind == "ai_reinvention_assessment": return "reinvention_candidate_fact"
    if "market_participant" in obj.kind: return "participant_candidate_fact"
    if "enterprise" in obj.kind or obj.kind == "entity": return "enterprise_candidate_fact"
    if "industry" in obj.kind or obj.kind in {"subsector", "value_chain", "economic_pool"}: return "industry_candidate_fact"
    return "candidate_fact"
