"""Governed source registry for Flora live evidence v0.7."""
from __future__ import annotations

from pathlib import Path
import json

from pydantic import BaseModel, HttpUrl


class EnterpriseScope(BaseModel):
    canonical_enterprise_id: str
    display_name: str
    aliases: list[str] = []
    collection_profile: str | None = None
    permitted_source_ids: list[str] = []
    run_id: str | None = None
    collection_mode: str = "live_plus_seeded"


class SourceRecord(BaseModel):
    source_id: str
    organisation: str
    source_name: str
    source_type: str
    url: HttpUrl
    sector: str
    evidence_tier: str
    expected_signal_types: list[str]
    enabled: bool = True
    coverage_role: str = "primary"
    notes: str = ""
    source_classification: str = "focused_page"
    preferred_child_paths: list[str] = []
    canonical_enterprise_id: str | None = None
    collection_purpose: str = "live evidence collection"
    authority_tier: str | None = None
    freshness_expectation: str | None = None
    profile_passes: list[str] = []

SOURCES: tuple[SourceRecord, ...] = (

    # Compatibility multi-source coverage for original pilot organisations.
    SourceRecord(source_id='thames-water-investors', organisation='Thames Water', source_name='Thames Water investors', source_type='investor_results', source_classification='report', url='https://www.thameswater.co.uk/about-us/investors', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['investment', 'operational performance', 'resilience'], coverage_role='secondary', notes='Investor source retained for governed triangulation.'),
    SourceRecord(source_id='thames-water-ofwat', organisation='Thames Water', source_name='Ofwat news', source_type='regulator_publications', source_classification='regulator_report', url='https://www.ofwat.gov.uk/news/', sector='Utilities', evidence_tier='tier_1_regulator', expected_signal_types=['regulation', 'operational performance', 'customer service'], coverage_role='regulator', notes='Regulator landing page, not a search URL.'),
    SourceRecord(source_id='bt-investors', organisation='BT', source_name='BT investors', source_type='investor_results', url='https://www.bt.com/about/investors', source_classification='landing_page', preferred_child_paths=['financial-reporting-and-news/annual-reports', 'financial-reporting-and-news/quarterly-results'], sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['digital transformation', 'cost reduction', 'network'], coverage_role='secondary', notes='Investor source retained for governed triangulation.'),
    SourceRecord(source_id='bt-annual-reports', organisation='BT', source_name='BT annual reports', source_type='annual_report_landing', source_classification='annual_report', url='https://www.bt.com/about/investors/financial-reporting-and-news/annual-reports', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['Financial Results', 'Annual Report Strategy', 'Capital Allocation', 'Cost Pressure', 'Productivity Target', 'Network Investment'], enabled=False, coverage_role='primary', notes='BT-specific annual report landing page included for governed financial and strategy evidence.'),
    SourceRecord(source_id='bt-quarterly-results', organisation='BT', source_name='BT financial results', source_type='investor_results', source_classification='report', url='https://www.bt.com/about/investors/financial-reporting-and-news/quarterly-results', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['Financial Results', 'Capital Allocation', 'Cost Pressure', 'Productivity Target', 'Network Investment'], enabled=False, coverage_role='primary', notes='BT-specific results page included for current revenue, EBITDA, cash flow, capex and transformation targets.'),
    SourceRecord(source_id='bt-investor-presentations', organisation='BT', source_name='BT investor presentations', source_type='investor_presentations', url='https://www.bt.com/about/investors/financial-reporting-and-news/events-and-presentations', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['Annual Report Strategy', 'Executive Priority', 'Transformation Programme', 'Network Investment'], enabled=False, coverage_role='secondary', notes='Governed investor materials for strategy interpretation; no broad crawling.'),
    SourceRecord(source_id='bt-consensus', organisation='BT', source_name='BT investor consensus', source_type='investor_consensus', url='https://www.bt.com/about/investors/financial-reporting-and-news/consensus', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['Analyst / market evidence'], enabled=False, coverage_role='secondary', notes='Public BT consensus page; if inaccessible, Observatory labels analyst report evidence unavailable.'),
    SourceRecord(source_id='openreach-investor-context', organisation='BT', source_name='Openreach news', source_type='official_newsroom', source_classification='news_item', url='https://www.openreach.com/news', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['Network Investment', 'Customer Operations', 'Technology Estate'], enabled=False, coverage_role='secondary', notes='Openreach public source included because Openreach is central to BT fixed network economics.'),
    SourceRecord(source_id='ofcom-telecoms-security', organisation='BT', source_name='Ofcom telecoms security and resilience', source_type='regulator_publications', source_classification='regulator_report', url='https://www.ofcom.org.uk/phones-and-broadband/telecoms-infrastructure/security-resilience/', sector='Telecommunications', evidence_tier='tier_1_regulator', expected_signal_types=['Regulatory Pressure', 'Cyber Risk'], enabled=False, coverage_role='regulator', notes='Stable regulator source for telecoms security and resilience obligations.'),
    SourceRecord(source_id='ofcom-service-quality', organisation='BT', source_name='Ofcom telecoms service quality', source_type='regulator_publications', source_classification='regulator_report', url='https://www.ofcom.org.uk/phones-and-broadband/service-quality/', sector='Telecommunications', evidence_tier='tier_1_regulator', expected_signal_types=['Customer Operations', 'Regulatory Pressure'], enabled=False, coverage_role='regulator', notes='Stable regulator source for customer outcomes and service-assurance pressure.'),
    SourceRecord(source_id='dsit-telecoms-policy', organisation='BT', source_name='DSIT telecoms policy', source_type='govuk_policy', url='https://www.gov.uk/government/collections/telecoms', sector='Telecommunications', evidence_tier='tier_1_public_body', expected_signal_types=['Political', 'Regulatory Pressure', 'Network Investment'], enabled=False, coverage_role='policy', notes='GOV.UK telecoms policy collection included for PESTLE context.'),
    SourceRecord(source_id='ncsc-cni-guidance', organisation='BT', source_name='NCSC critical national infrastructure guidance', source_type='official_guidance', url='https://www.ncsc.gov.uk/section/advice-guidance/all-topics?topics=critical-national-infrastructure', sector='Telecommunications', evidence_tier='tier_1_public_body', expected_signal_types=['Cyber Risk', 'Regulatory Pressure'], enabled=False, coverage_role='policy', notes='NCSC public guidance included for cyber-resilience context; not BT-specific budget evidence.'),
    SourceRecord(source_id='bt-ofcom', organisation='BT', source_name='Ofcom news centre', source_type='regulator_publications', source_classification='regulator_report', url='https://www.ofcom.org.uk/news-centre/', sector='Telecommunications', evidence_tier='tier_1_regulator', expected_signal_types=['regulation', 'customer service', 'network'], coverage_role='regulator', notes='Regulator landing page, not a search URL.'),
    SourceRecord(source_id='united-utilities-results', organisation='United Utilities', source_name='United Utilities results centre', source_type='investor_results', source_classification='report', url='https://www.unitedutilities.com/corporate/investors/results-centre/', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['investment', 'operational performance'], coverage_role='secondary', notes='Stable governed investor source.'),
    SourceRecord(source_id='united-utilities-news', organisation='United Utilities', source_name='United Utilities news', source_type='official_newsroom', source_classification='news_item', url='https://www.unitedutilities.com/corporate/newsroom/', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['customer service', 'investment', 'resilience'], coverage_role='primary', notes='Stable governed public HTML source.'),
    SourceRecord(source_id='sse-results', organisation='SSE', source_name='SSE results and reports', source_type='investor_results', source_classification='report', url='https://www.sse.com/investors/results-and-reports/', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['investment', 'network', 'resilience'], coverage_role='secondary', notes='Stable governed investor source.'),
    SourceRecord(source_id='sky-results', organisation='Sky', source_name='Comcast quarterly results', source_type='investor_results', source_classification='report', url='https://www.cmcsa.com/financials/quarterly-results', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['customer experience', 'data', 'cloud'], coverage_role='secondary', notes='Parent investor source for Sky.'),
    SourceRecord(source_id='bbc-annual-report', organisation='BBC', source_name='BBC annual reports', source_type='annual_report_landing', source_classification='annual_report', url='https://www.bbc.com/aboutthebbc/reports/annualreport', sector='Media', evidence_tier='tier_1_public_body', expected_signal_types=['digital transformation', 'efficiency', 'customer experience'], coverage_role='secondary', notes='Annual report landing page.'),

    SourceRecord(source_id='united-utilities-ofwat', organisation='United Utilities', source_name='Ofwat news', source_type='regulator_publications', source_classification='regulator_report', url='https://www.ofwat.gov.uk/news/', sector='Utilities', evidence_tier='tier_1_regulator', expected_signal_types=['regulation', 'operational performance'], coverage_role='regulator', notes='Regulator source for water-sector context.'),
    SourceRecord(source_id='sse-ofgem', organisation='SSE', source_name='Ofgem news and views', source_type='regulator_publications', source_classification='regulator_report', url='https://www.ofgem.gov.uk/news-and-views', sector='Energy', evidence_tier='tier_1_regulator', expected_signal_types=['regulation', 'network', 'investment'], coverage_role='regulator', notes='Regulator source for energy-sector context.'),
    SourceRecord(source_id='sky-ofcom', organisation='Sky', source_name='Ofcom news centre', source_type='regulator_publications', source_classification='regulator_report', url='https://www.ofcom.org.uk/news-centre/', sector='Media', evidence_tier='tier_1_regulator', expected_signal_types=['regulation', 'customer service'], coverage_role='regulator', notes='Regulator source for communications and media context.'),
    SourceRecord(source_id='bbc-ofcom', organisation='BBC', source_name='Ofcom news centre', source_type='regulator_publications', source_classification='regulator_report', url='https://www.ofcom.org.uk/news-centre/', sector='Media', evidence_tier='tier_1_regulator', expected_signal_types=['regulation', 'customer service'], coverage_role='regulator', notes='Regulator source for media context.'),
    SourceRecord(source_id='bt-strategy', organisation='BT', source_name='BT strategy overview', source_type='strategy_page', url='https://www.bt.com/about/strategy', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['digital transformation', 'customer experience', 'network'], enabled=False, coverage_role='context', notes='Disabled pending fetch reliability.'),
    SourceRecord(source_id='bbc-rss', organisation='BBC', source_name='BBC press office feed', source_type='official_rss_or_feed', url='https://feeds.bbci.co.uk/news/rss.xml', sector='Media', evidence_tier='tier_2_feed', expected_signal_types=['customer experience', 'data'], enabled=False, coverage_role='context', notes='Disabled because collection expects HTML.'),
    SourceRecord(source_id='thames-water-official-newsroom', organisation='Thames Water', source_name='Thames Water governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.thameswater.co.uk/news', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='united-utilities-official-newsroom', organisation='United Utilities', source_name='United Utilities governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.unitedutilities.com/corporate/newsroom/', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='severn-trent-official-newsroom', organisation='Severn Trent', source_name='Severn Trent governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.severntrent.com/news/', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='southern-water-official-newsroom', organisation='Southern Water', source_name='Southern Water governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.southernwater.co.uk/latest-news/', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='yorkshire-water-official-newsroom', organisation='Yorkshire Water', source_name='Yorkshire Water governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.yorkshirewater.com/news-media/', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='anglian-water-official-newsroom', organisation='Anglian Water', source_name='Anglian Water governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.anglianwater.co.uk/news/', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='northumbrian-water-official-newsroom', organisation='Northumbrian Water', source_name='Northumbrian Water governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.nwl.co.uk/news/', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='south-west-water-pennon-official-newsroom', organisation='South West Water / Pennon', source_name='South West Water / Pennon governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.pennon-group.co.uk/media/news', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='wessex-water-official-newsroom', organisation='Wessex Water', source_name='Wessex Water governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.wessexwater.co.uk/news', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='affinity-water-official-newsroom', organisation='Affinity Water', source_name='Affinity Water governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.affinitywater.co.uk/news', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='portsmouth-water-official-newsroom', organisation='Portsmouth Water', source_name='Portsmouth Water governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.portsmouthwater.co.uk/news/', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ses-water-official-newsroom', organisation='SES Water', source_name='SES Water governed source', source_type='official_newsroom', source_classification='news_item', url='https://seswater.co.uk/news', sector='Utilities', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='national-grid-official-newsroom', organisation='National Grid', source_name='National Grid governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.nationalgrid.com/media-centre/press-releases', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='sse-official-newsroom', organisation='SSE', source_name='SSE governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.sse.com/news-and-views/', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='centrica-official-newsroom', organisation='Centrica', source_name='Centrica governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.centrica.com/media-centre/news/', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='edf-energy-uk-official-newsroom', organisation='EDF Energy UK', source_name='EDF Energy UK governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.edfenergy.com/media-centre', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='octopus-energy-official-newsroom', organisation='Octopus Energy', source_name='Octopus Energy governed source', source_type='official_newsroom', source_classification='news_item', url='https://octopus.energy/press/', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='scottishpower-official-newsroom', organisation='ScottishPower', source_name='ScottishPower governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.scottishpower.com/news', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='e-on-uk-official-newsroom', organisation='E.ON UK', source_name='E.ON UK governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.eonenergy.com/about-us/media-centre.html', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='rwe-uk-official-newsroom', organisation='RWE UK', source_name='RWE UK governed source', source_type='official_newsroom', source_classification='news_item', url='https://uk.rwe.com/press-and-news/', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='drax-official-newsroom', organisation='Drax', source_name='Drax governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.drax.com/press_release/', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ovo-energy-official-newsroom', organisation='OVO Energy', source_name='OVO Energy governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.ovoenergy.com/press', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='uk-power-networks-official-newsroom', organisation='UK Power Networks', source_name='UK Power Networks governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.ukpowernetworks.co.uk/news', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='sp-energy-networks-official-newsroom', organisation='SP Energy Networks', source_name='SP Energy Networks governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.spenergynetworks.co.uk/news/', sector='Energy', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='bt-official-newsroom', organisation='BT', source_name='BT governed source', source_type='official_newsroom', source_classification='news_item', url='https://newsroom.bt.com/', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='vodafone-official-newsroom', organisation='Vodafone', source_name='Vodafone governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.vodafone.com/news', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='virgin-media-o2-official-newsroom', organisation='Virgin Media O2', source_name='Virgin Media O2 governed source', source_type='official_newsroom', source_classification='news_item', url='https://news.virginmediao2.co.uk/', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='talktalk-official-newsroom', organisation='TalkTalk', source_name='TalkTalk governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.talktalkgroup.com/newsroom/', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='three-uk-official-newsroom', organisation='Three UK', source_name='Three UK governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.threemediacentre.co.uk/', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='openreach-official-newsroom', organisation='Openreach', source_name='Openreach governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.openreach.com/news', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='cityfibre-official-newsroom', organisation='CityFibre', source_name='CityFibre governed source', source_type='official_newsroom', source_classification='news_item', url='https://cityfibre.com/news', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='hyperoptic-official-newsroom', organisation='Hyperoptic', source_name='Hyperoptic governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.hyperoptic.com/press/', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='kcom-official-newsroom', organisation='KCOM', source_name='KCOM governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.kcom.com/home/discover/categories/news/', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='gamma-communications-official-newsroom', organisation='Gamma Communications', source_name='Gamma Communications governed source', source_type='official_newsroom', source_classification='news_item', url='https://gammagroup.co/news/', sector='Telecommunications', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='sky-official-newsroom', organisation='Sky', source_name='Sky governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.skygroup.sky/media-centre/', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='bbc-official-newsroom', organisation='BBC', source_name='BBC governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.bbc.co.uk/mediacentre/', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='itv-official-newsroom', organisation='ITV', source_name='ITV governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.itv.com/presscentre', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='channel-4-official-newsroom', organisation='Channel 4', source_name='Channel 4 governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.channel4.com/press/', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='channel-5-paramount-uk-official-newsroom', organisation='Channel 5 / Paramount UK', source_name='Channel 5 / Paramount UK governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.paramount.com/press', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='the-guardian-official-newsroom', organisation='The Guardian', source_name='The Guardian governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.theguardian.com/gnm-press-office', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='news-uk-official-newsroom', organisation='News UK', source_name='News UK governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.news.co.uk/latest-news/', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='dmg-media-official-newsroom', organisation='DMG Media', source_name='DMG Media governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.dmgmedia.co.uk/news/', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='reach-plc-official-newsroom', organisation='Reach plc', source_name='Reach plc governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.reachplc.com/news/', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='global-official-newsroom', organisation='Global', source_name='Global governed source', source_type='official_newsroom', source_classification='news_item', url='https://global.com/news/', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='bauer-media-official-newsroom', organisation='Bauer Media', source_name='Bauer Media governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.bauermedia.co.uk/news/', sector='Media', evidence_tier='tier_1_company', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='premier-league-official-newsroom', organisation='Premier League', source_name='Premier League governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.premierleague.com/news', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='the-football-association-official-newsroom', organisation='The Football Association', source_name='The Football Association governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.thefa.com/news', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='england-and-wales-cricket-board-official-newsroom', organisation='England and Wales Cricket Board', source_name='England and Wales Cricket Board governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.ecb.co.uk/news', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='rugby-football-union-official-newsroom', organisation='Rugby Football Union', source_name='Rugby Football Union governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.englandrugby.com/news', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='wimbledon-aeltc-official-newsroom', organisation='Wimbledon / AELTC', source_name='Wimbledon / AELTC governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.wimbledon.com/en_GB/news/index.html', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='british-olympic-association-official-newsroom', organisation='British Olympic Association', source_name='British Olympic Association governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.teamgb.com/news', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='uk-sport-official-newsroom', organisation='UK Sport', source_name='UK Sport governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.uksport.gov.uk/news', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='sport-england-official-newsroom', organisation='Sport England', source_name='Sport England governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.sportengland.org/news', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='england-netball-official-newsroom', organisation='England Netball', source_name='England Netball governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.englandnetball.co.uk/news/', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='british-cycling-official-newsroom', organisation='British Cycling', source_name='British Cycling governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.britishcycling.org.uk/about/article/bc-news', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='formula-1-silverstone-official-newsroom', organisation='Formula 1 / Silverstone', source_name='Formula 1 / Silverstone governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.silverstone.co.uk/news', sector='Sport', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ministry-of-defence-govuk-organisation', organisation='Ministry of Defence', source_name='Ministry of Defence governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/ministry-of-defence', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='dwp-govuk-organisation', organisation='DWP', source_name='DWP governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/department-for-work-pensions', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ministry-of-justice-govuk-organisation', organisation='Ministry of Justice', source_name='Ministry of Justice governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/ministry-of-justice', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='hmrc-govuk-organisation', organisation='HMRC', source_name='HMRC governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/hm-revenue-customs', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='defra-govuk-organisation', organisation='DEFRA', source_name='DEFRA governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='department-of-health-and-social-care-govuk-organisation', organisation='Department of Health and Social Care', source_name='Department of Health and Social Care governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/department-of-health-and-social-care', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='nhs-england-official-newsroom', organisation='NHS England', source_name='NHS England governed source', source_type='official_newsroom', source_classification='news_item', url='https://www.england.nhs.uk/news/', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='home-office-govuk-organisation', organisation='Home Office', source_name='Home Office governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/home-office', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='cabinet-office-govuk-organisation', organisation='Cabinet Office', source_name='Cabinet Office governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/cabinet-office', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='department-for-education-govuk-organisation', organisation='Department for Education', source_name='Department for Education governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/department-for-education', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='department-for-transport-govuk-organisation', organisation='Department for Transport', source_name='Department for Transport governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/department-for-transport', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='dsit-govuk-organisation', organisation='DSIT', source_name='DSIT governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/department-for-science-innovation-and-technology', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='desnz-govuk-organisation', organisation='DESNZ', source_name='DESNZ governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/department-for-energy-security-and-net-zero', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='mhclg-govuk-organisation', organisation='MHCLG', source_name='MHCLG governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/ministry-of-housing-communities-local-government', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='fcdo-govuk-organisation', organisation='FCDO', source_name='FCDO governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/foreign-commonwealth-development-office', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ukhsa-govuk-organisation', organisation='UKHSA', source_name='UKHSA governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/uk-health-security-agency', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='environment-agency-govuk-organisation', organisation='Environment Agency', source_name='Environment Agency governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/environment-agency', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='hm-treasury-govuk-organisation', organisation='HM Treasury', source_name='HM Treasury governed source', source_type='govuk_organisation', url='https://www.gov.uk/government/organisations/hm-treasury', sector='Public Sector', evidence_tier='tier_1_public_body', expected_signal_types=['Service Transformation', 'Digital Modernisation', 'Legacy Technology', 'Operational Efficiency', 'Spending Pressure', 'Citizen Experience', 'Cyber Resilience', 'AI Readiness', 'Procurement Readiness', 'Shared Services', 'Policy Reform'], enabled=True, coverage_role='primary', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ofwat-regulator-news', organisation='Ofwat', source_name='Ofwat governed source', source_type='regulator_news', url='https://www.ofwat.gov.uk/news/', sector='Regulators', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='regulator', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ofgem-regulator-news', organisation='Ofgem', source_name='Ofgem governed source', source_type='regulator_news', url='https://www.ofgem.gov.uk/news-and-views', sector='Regulators', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='regulator', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ofcom-regulator-news', organisation='Ofcom', source_name='Ofcom governed source', source_type='regulator_news', url='https://www.ofcom.org.uk/news-centre/', sector='Regulators', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='regulator', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='cma-regulator-news', organisation='CMA', source_name='CMA governed source', source_type='regulator_news', url='https://www.gov.uk/government/organisations/competition-and-markets-authority', sector='Regulators', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='regulator', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ico-regulator-news', organisation='ICO', source_name='ICO governed source', source_type='regulator_news', url='https://ico.org.uk/about-the-ico/media-centre/news-and-blogs/', sector='Regulators', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='regulator', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='national-audit-office-regulator-news', organisation='National Audit Office', source_name='National Audit Office governed source', source_type='regulator_news', url='https://www.nao.org.uk/reports/', sector='Regulators', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='regulator', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='infrastructure-and-projects-authority-regulator-news', organisation='Infrastructure and Projects Authority', source_name='Infrastructure and Projects Authority governed source', source_type='regulator_news', url='https://www.gov.uk/government/organisations/infrastructure-and-projects-authority', sector='Regulators', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='regulator', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='uk-regulators-network-regulator-news', organisation='UK Regulators Network', source_name='UK Regulators Network governed source', source_type='regulator_news', url='https://www.ukrn.org.uk/news/', sector='Regulators', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='regulator', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='sport-england-regulator-news', organisation='Sport England', source_name='Sport England governed source', source_type='regulator_news', url='https://www.sportengland.org/news', sector='Regulators', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='regulator', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='uk-sport-regulator-news', organisation='UK Sport', source_name='UK Sport governed source', source_type='regulator_news', url='https://www.uksport.gov.uk/news', sector='Regulators', evidence_tier='tier_1_public_body', expected_signal_types=['AI', 'digital transformation', 'customer experience', 'operational performance', 'investment', 'resilience', 'procurement', 'cloud', 'data'], enabled=True, coverage_role='regulator', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ibm-supplier-newsroom', organisation='IBM', source_name='IBM governed source', source_type='supplier_newsroom', url='https://newsroom.ibm.com/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='accenture-supplier-newsroom', organisation='Accenture', source_name='Accenture governed source', source_type='supplier_newsroom', url='https://newsroom.accenture.com/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='capgemini-supplier-newsroom', organisation='Capgemini', source_name='Capgemini governed source', source_type='supplier_newsroom', url='https://www.capgemini.com/news/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='deloitte-supplier-newsroom', organisation='Deloitte', source_name='Deloitte governed source', source_type='supplier_newsroom', url='https://www.deloitte.com/uk/en/about/press-room.html', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='kpmg-supplier-newsroom', organisation='KPMG', source_name='KPMG governed source', source_type='supplier_newsroom', url='https://kpmg.com/uk/en/home/media.html', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='pwc-supplier-newsroom', organisation='PwC', source_name='PwC governed source', source_type='supplier_newsroom', url='https://www.pwc.co.uk/press-room.html', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='cognizant-supplier-newsroom', organisation='Cognizant', source_name='Cognizant governed source', source_type='supplier_newsroom', url='https://news.cognizant.com/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='cgi-supplier-newsroom', organisation='CGI', source_name='CGI governed source', source_type='supplier_newsroom', url='https://www.cgi.com/uk/en-gb/news', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='tcs-supplier-newsroom', organisation='TCS', source_name='TCS governed source', source_type='supplier_newsroom', url='https://www.tcs.com/who-we-are/newsroom', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='infosys-supplier-newsroom', organisation='Infosys', source_name='Infosys governed source', source_type='supplier_newsroom', url='https://www.infosys.com/newsroom/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='wipro-supplier-newsroom', organisation='Wipro', source_name='Wipro governed source', source_type='supplier_newsroom', url='https://www.wipro.com/newsroom/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='atos-eviden-supplier-newsroom', organisation='Atos / Eviden', source_name='Atos / Eviden governed source', source_type='supplier_newsroom', url='https://atos.net/en/newsroom', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='fujitsu-supplier-newsroom', organisation='Fujitsu', source_name='Fujitsu governed source', source_type='supplier_newsroom', url='https://www.fujitsu.com/uk/news/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='sopra-steria-supplier-newsroom', organisation='Sopra Steria', source_name='Sopra Steria governed source', source_type='supplier_newsroom', url='https://www.soprasteria.co.uk/newsroom', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='dxc-technology-supplier-newsroom', organisation='DXC Technology', source_name='DXC Technology governed source', source_type='supplier_newsroom', url='https://dxc.com/us/en/about-us/newsroom', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='ntt-data-supplier-newsroom', organisation='NTT DATA', source_name='NTT DATA governed source', source_type='supplier_newsroom', url='https://uk.nttdata.com/news', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='oracle-supplier-newsroom', organisation='Oracle', source_name='Oracle governed source', source_type='supplier_newsroom', url='https://www.oracle.com/news/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='microsoft-supplier-newsroom', organisation='Microsoft', source_name='Microsoft governed source', source_type='supplier_newsroom', url='https://news.microsoft.com/en-gb/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='servicenow-supplier-newsroom', organisation='ServiceNow', source_name='ServiceNow governed source', source_type='supplier_newsroom', url='https://www.servicenow.com/uk/company/media/press-room.html', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='salesforce-supplier-newsroom', organisation='Salesforce', source_name='Salesforce governed source', source_type='supplier_newsroom', url='https://www.salesforce.com/uk/news/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='sap-supplier-newsroom', organisation='SAP', source_name='SAP governed source', source_type='supplier_newsroom', url='https://news.sap.com/uk/', sector='Competitors', evidence_tier='tier_1_supplier', expected_signal_types=['AI Reinvention Positioning', 'Managed Services', 'Cloud Modernisation', 'Consulting Growth', 'Sector Proposition', 'Partnership Ecosystem', 'Competitive Threat', 'Delivery Capability'], enabled=True, coverage_role='competitor', notes='Stable governed public HTML source selected for Flora v0.7 coverage.'),
    SourceRecord(source_id='taxonomy-official-home', organisation='BT', source_name='Taxonomy exemplar official_home', source_type='official_home', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-official-press-release', organisation='BT', source_name='Taxonomy exemplar official_press_release', source_type='official_press_release', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-official-blog', organisation='BT', source_name='Taxonomy exemplar official_blog', source_type='official_blog', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-official-investor-relations', organisation='BT', source_name='Taxonomy exemplar official_investor_relations', source_type='official_investor_relations', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-official-results', organisation='BT', source_name='Taxonomy exemplar official_results', source_type='official_results', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-official-annual-reports', organisation='BT', source_name='Taxonomy exemplar official_annual_reports', source_type='official_annual_reports', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-official-strategy', organisation='BT', source_name='Taxonomy exemplar official_strategy', source_type='official_strategy', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-official-sustainability', organisation='BT', source_name='Taxonomy exemplar official_sustainability', source_type='official_sustainability', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-regulator-publications', organisation='BT', source_name='Taxonomy exemplar regulator_publications', source_type='regulator_publications', source_classification='regulator_report', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-regulator-consultations', organisation='BT', source_name='Taxonomy exemplar regulator_consultations', source_type='regulator_consultations', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-govuk-news', organisation='Cabinet Office', source_name='Taxonomy exemplar govuk_news', source_type='govuk_news', url='https://www.gov.uk/government/organisations/cabinet-office', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-govuk-publications', organisation='Cabinet Office', source_name='Taxonomy exemplar govuk_publications', source_type='govuk_publications', url='https://www.gov.uk/government/organisations/cabinet-office', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-govuk-policy', organisation='Cabinet Office', source_name='Taxonomy exemplar govuk_policy', source_type='govuk_policy', url='https://www.gov.uk/government/organisations/cabinet-office', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-govuk-procurement', organisation='Cabinet Office', source_name='Taxonomy exemplar govuk_procurement', source_type='govuk_procurement', url='https://www.gov.uk/government/organisations/cabinet-office', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-public-body-reports', organisation='BT', source_name='Taxonomy exemplar public_body_reports', source_type='public_body_reports', url='https://newsroom.bt.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-nao-reports', organisation='National Audit Office', source_name='Taxonomy exemplar nao_reports', source_type='nao_reports', url='https://www.nao.org.uk/reports/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-contracts-finder', organisation='Cabinet Office', source_name='Taxonomy exemplar contracts_finder', source_type='contracts_finder', url='https://www.gov.uk/government/organisations/cabinet-office', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-find-tender', organisation='Cabinet Office', source_name='Taxonomy exemplar find_tender', source_type='find_tender', url='https://www.gov.uk/government/organisations/cabinet-office', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-supplier-case-studies', organisation='IBM', source_name='Taxonomy exemplar supplier_case_studies', source_type='supplier_case_studies', url='https://newsroom.ibm.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-supplier-insights', organisation='IBM', source_name='Taxonomy exemplar supplier_insights', source_type='supplier_insights', url='https://newsroom.ibm.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
    SourceRecord(source_id='taxonomy-partner-ecosystem', organisation='IBM', source_name='Taxonomy exemplar partner_ecosystem', source_type='partner_ecosystem', url='https://newsroom.ibm.com/', sector='Context', evidence_tier='tier_2_context', expected_signal_types=['context'], enabled=False, coverage_role='context', notes='Disabled taxonomy coverage exemplar; not collected by default.'),
)

TARGET_ORGANISATIONS: tuple[str, ...] = tuple(dict.fromkeys(source.organisation for source in SOURCES))
ALIASES = {"thameswater": "Thames Water", "nationalgrid": "National Grid", "bt": "BT", "vodafone": "Vodafone"}
ALIASES.update({org.replace(" ", "").replace("_", "").replace("-", "").replace("/", "").replace(".", "").lower(): org for org in TARGET_ORGANISATIONS})


def canonical_organisation(value: str) -> str:
    return ALIASES.get(value.replace(" ", "").replace("_", "").replace("-", "").replace("/", "").replace(".", "").lower(), value)


def enabled_sources(organisation: str | None = None) -> list[SourceRecord]:
    org = canonical_organisation(organisation) if organisation else None
    return [s for s in SOURCES if s.enabled and (org is None or s.organisation == org)]


def organisations_without_enabled_sources() -> list[str]:
    enabled = {s.organisation for s in SOURCES if s.enabled}
    return sorted(org for org in TARGET_ORGANISATIONS if org not in enabled)

PROFILE_DIR = Path(__file__).resolve().parents[4] / "config/flora/collection_profiles"
COLLECTION_MODES = {"live_authoritative", "live_plus_seeded", "test_fixture"}
_DEFAULT_ENTERPRISE_ALIASES = {
    "bt": "bt-group-plc",
    "bt group": "bt-group-plc",
    "bt group plc": "bt-group-plc",
    "british telecommunications": "bt-group-plc",
}


def _norm_identity(value: str) -> str:
    return " ".join(str(value or "").casefold().replace(".", "").split())


def load_collection_profile(profile_id: str) -> dict:
    path = PROFILE_DIR / f"{profile_id}.json"
    if not path.exists():
        raise ValueError(f"Unknown Flora collection profile: {profile_id}")
    return json.loads(path.read_text(encoding="utf-8"))


def configured_enterprise_aliases() -> dict[str, str]:
    aliases = dict(_DEFAULT_ENTERPRISE_ALIASES)
    for source in SOURCES:
        cid = source.canonical_enterprise_id or source.organisation
        aliases[_norm_identity(source.organisation)] = cid
        aliases[_norm_identity(source.organisation).replace(" ", "")] = cid
    if PROFILE_DIR.exists():
        for path in PROFILE_DIR.glob("*.json"):
            data = json.loads(path.read_text(encoding="utf-8"))
            ent = data.get("enterprise_scope", {})
            cid = ent.get("canonical_enterprise_id") or data.get("profile_id")
            for name in [cid, ent.get("display_name"), *(ent.get("aliases") or [])]:
                if name:
                    aliases[_norm_identity(str(name))] = cid
    return aliases


def canonical_enterprise_id(name: str | None) -> str | None:
    if name is None:
        return None
    key = _norm_identity(name)
    aliases = configured_enterprise_aliases()
    if key in aliases:
        return aliases[key]
    return key.replace(" ", "-")


def canonical_organisation(name: str) -> str:
    cid = canonical_enterprise_id(name)
    if cid == "bt-group-plc":
        return "BT Group plc"
    lookup = {_norm_identity(s.organisation): s.organisation for s in SOURCES}
    return lookup.get(_norm_identity(name), name)


def source_canonical_enterprise_id(source: SourceRecord) -> str:
    return source.canonical_enterprise_id or canonical_enterprise_id(source.organisation) or source.organisation


def collection_scope(profile_id: str, *, run_id: str | None = None, mode: str | None = None, passes: list[str] | None = None) -> EnterpriseScope:
    profile = load_collection_profile(profile_id)
    ent = profile["enterprise_scope"]
    selected_mode = mode or profile.get("default_collection_mode", "live_plus_seeded")
    if selected_mode not in COLLECTION_MODES:
        raise ValueError(f"Unsupported collection mode: {selected_mode}")
    sources = profile.get("sources", [])
    selected_passes = set(passes or profile.get("default_passes") or [])
    permitted = [s["source_id"] for s in sources if s.get("enabled", True) and (not selected_passes or selected_passes.intersection(s.get("passes", [])))]
    return EnterpriseScope(canonical_enterprise_id=ent["canonical_enterprise_id"], display_name=ent["display_name"], aliases=ent.get("aliases", []), collection_profile=profile_id, permitted_source_ids=permitted, run_id=run_id, collection_mode=selected_mode)


def profile_sources(profile_id: str, *, passes: list[str] | None = None) -> list[SourceRecord]:
    profile = load_collection_profile(profile_id)
    ent = profile["enterprise_scope"]
    selected_passes = set(passes or profile.get("default_passes") or [])
    records = []
    for row in profile.get("sources", []):
        if not row.get("enabled", True) or (selected_passes and not selected_passes.intersection(row.get("passes", []))):
            continue
        records.append(SourceRecord(source_id=row["source_id"], organisation=ent["display_name"], source_name=row.get("source_name", row["source_id"]), source_type=row["source_type"], url=row["url"], sector=row.get("sector", "Telecommunications"), evidence_tier=row.get("authority_tier", "tier_1_company"), expected_signal_types=row.get("expected_signal_types", []), enabled=True, coverage_role=row.get("collection_purpose", "primary"), notes=row.get("notes", ""), source_classification=row.get("source_classification", "focused_page"), preferred_child_paths=[], canonical_enterprise_id=ent["canonical_enterprise_id"], collection_purpose=row.get("collection_purpose", ""), authority_tier=row.get("authority_tier"), freshness_expectation=row.get("freshness_expectation"), profile_passes=row.get("passes", [])))
    return records


def enabled_sources(organisation: str | None = None, *, profile_id: str | None = None, passes: list[str] | None = None) -> list[SourceRecord]:
    if profile_id:
        return profile_sources(profile_id, passes=passes)
    canonical = canonical_enterprise_id(organisation) if organisation else None
    return [s for s in SOURCES if s.enabled and (canonical is None or source_canonical_enterprise_id(s) == canonical)]
