"""Governed UK Banking portfolio projections for Flora.

Deterministic, fixture-backed presentation projections. They are transient views
over governed evidence-like source packages and do not write canonical models.
"""
from __future__ import annotations

from dataclasses import dataclass
from html import escape
from pathlib import Path
import json

from cios.applications.flora.enterprise_intelligence.models import stable_hash
from cios.applications.flora.workspace.views import _page

THEMES = (
    "Customer and digital engagement",
    "Deposits and balance-sheet economics",
    "Cost transformation and productivity",
    "Technology, cloud and AI",
    "Operational resilience and third-party dependency",
    "Brand, channel and operating-model simplification",
    "Regulation and control",
    "Growth, capital and investment priorities",
)

BANKS = {
 "lloyds": {"id":"BK-ENT-001","name":"Lloyds Banking Group","scope":"UK banking group","period":"FY2024-Q1 2025","summary":"Digital engagement, deposit economics and technology transformation are changing together while outcome evidence remains incomplete.","themes":["Customer and digital engagement","Deposits and balance-sheet economics","Technology, cloud and AI"],"evidence":"available","unknowns":["Whether increased mobile acquisition translates into deeper primary relationships","How investment is allocated between productivity, resilience and growth","Customer outcome evidence from brand and channel simplification"],"changes":[("Mobile and digital engagement remains central","Company reporting describes continued growth in digital activity and mobile-led engagement.","Commercially relevant because relationship depth and channel mix affect how transformation priorities are framed.","fact plus bounded interpretation"),("Deposit economics remain material","Reported deposit, margin and balance-sheet commentary make funding economics a near-term management theme.","Useful for understanding pressure around customer value, retention and capital allocation.","fact plus bounded interpretation"),("Technology transformation is accumulating","Governed observations connect platform modernisation, cloud/AI activity and productivity ambition.","Raises questions about delivery sequencing, resilience control and measurable outcomes.","interpretation from accumulated observations")],"distinctive":"UK-focused franchise where digital engagement, deposits and technology investment are visible in the same governed package.","sector":"Digital adoption, cost productivity, regulatory control and resilience are also visible across peers.","tensions":["Digital migration versus customer trust and inclusion","Cost reduction versus transformation investment"],"questions":["How is Lloyds assessing whether increased mobile acquisition is translating into deeper primary banking relationships?","How are transformation investments being prioritised between productivity, resilience and growth?","What customer outcomes will determine whether brand and channel simplification has succeeded?","Where does resilience evidence constrain the pace of cloud and AI adoption?","Which deposit-behaviour indicators would change management priorities over the next evidence period?"],"sources":["Lloyds governed semantic evaluation dataset", "Company-reported annual and quarterly reporting passages"]},
 "barclays": {"id":"BK-ENT-002","name":"Barclays","scope":"UK-headquartered bank including Barclays UK and group context","period":"FY2024-Q1 2025","summary":"Visible change concentrates on operating simplification, investment discipline and digital/productivity themes.","themes":["Cost transformation and productivity","Growth, capital and investment priorities","Customer and digital engagement"],"evidence":"available","unknowns":["How UK retail changes separate from group-wide investment-bank dynamics","Which simplification outcomes are realised versus planned","Comparable customer outcome evidence across peers"],"changes":[("Simplification and productivity are prominent","Company-reported material emphasises efficiency and simpler operating priorities.","Helps frame questions on where transformation capacity is being released or consumed.","fact plus bounded interpretation"),("Capital and investment priorities are visible","Evidence points to explicit prioritisation choices across businesses.","Commercially useful for understanding why timing and allocation questions matter now.","fact"),("Digital engagement is present but not fully comparable","Reported customer and digital signals exist, but peer-comparable measures are incomplete.","Prevents overclaiming relative digital position while still supporting account-specific questions.","fact with safe limit")],"distinctive":"The governed signal is more about portfolio simplification and capital discipline than a single UK retail-only change story.","sector":"Cost productivity and digital engagement are also visible across the banking portfolio.","tensions":["Cost reduction versus transformation investment","Growth and capital allocation versus operating simplification"],"questions":["Which simplification outcomes are Barclays using to judge whether productivity changes are translating into customer and colleague improvements?","How are investment priorities being balanced between UK retail change and broader group priorities?","Where is peer-comparable evidence insufficient to assess digital engagement progress?","What evidence would show whether cost transformation is enabling growth rather than only reducing expense?","How are resilience and third-party controls shaping transformation sequencing?"],"sources":["Human-curated deterministic fixture from public company reporting excerpts"]},
 "natwest": {"id":"BK-ENT-003","name":"NatWest Group","scope":"UK banking group","period":"FY2024-Q1 2025","summary":"Customer franchise, balance-sheet economics and simplification signals appear together, with unresolved outcome evidence.","themes":["Deposits and balance-sheet economics","Customer and digital engagement","Brand, channel and operating-model simplification"],"evidence":"available","unknowns":["Depth of customer relationship outcomes behind digital engagement","How simplification affects resilience and service inclusion","Comparability of deposit momentum across banks"],"changes":[("Customer and franchise activity is visible","Company-reported evidence describes customer and digital franchise progress.","Supports commercially specific questions about relationship quality and service outcomes.","fact plus bounded interpretation"),("Balance-sheet economics remain a live theme","Deposit and margin context remains material in current-period reporting.","Frames why retention, pricing and customer-value questions are timely.","fact"),("Simplification intersects with service outcomes","Governed observations indicate operating-model simplification alongside customer change.","Raises a tension between efficiency and trust/inclusion.","interpretation")],"distinctive":"A UK banking franchise story where customer, deposit and simplification themes are visible together.","sector":"Deposit economics, digital engagement and cost productivity are sector-consistent patterns.","tensions":["Digital migration versus customer trust and inclusion","Deposit economics versus uncertainty over capital allocation"],"questions":["How is NatWest testing whether digital engagement is deepening primary customer relationships?","Which deposit-behaviour signals would change current customer-value priorities?","How are simplification benefits being balanced against resilience, service and inclusion outcomes?","What evidence would distinguish sector-wide margin pressure from NatWest-specific deposit movement?","How are investment priorities changing as customer and balance-sheet signals accumulate?"],"sources":["Human-curated deterministic fixture from public company reporting excerpts"]},
 "hsbc-uk": {"id":"BK-ENT-004","name":"HSBC UK","scope":"UK ring-fenced bank within HSBC group","period":"FY2024-Q1 2025","summary":"Governed evidence supports a bounded UK-bank view, but group context limits some comparisons.","themes":["Regulation and control","Technology, cloud and AI","Operational resilience and third-party dependency"],"evidence":"partial","unknowns":["Which changes are specific to HSBC UK rather than wider HSBC group","Comparable UK customer and deposit outcomes","Supplier dependency evidence at UK-bank level"],"changes":[("UK scope requires careful separation","Evidence is sufficient to identify HSBC UK but not every group-wide claim can be treated as UK-bank proof.","Commercially important because account questions must not over-attribute group strategy to the UK bank.","safe interpretation"),("Control and resilience context is material","Banking regulation and operational resilience are relevant context for HSBC UK.","Useful for questions about constraints on transformation sequencing.","context with limits"),("Technology themes are visible but partially evidenced","Technology and AI/cloud themes are present, while UK-specific lineage is incomplete.","Supports inquiry, not conclusion, about UK-level implementation priorities.","partial evidence")],"distinctive":"The distinctive signal is the need to separate HSBC UK evidence from broader HSBC group context.","sector":"Resilience, regulatory control and technology acceleration are sector-wide context.","tensions":["Cloud and AI acceleration versus resilience and supplier control","Regulatory control versus operating-model change"],"questions":["Which current transformation priorities are specifically owned and measured within HSBC UK rather than at wider group level?","How are UK resilience requirements shaping the pace of technology and AI adoption?","What evidence would show customer outcomes from UK-specific digital change?","Where do third-party controls create constraints or dependencies for UK banking transformation?","How should sector regulatory context be separated from HSBC UK-specific change evidence?"],"sources":["Human-curated deterministic fixture from public company reporting excerpts"],"safe":"Some UK-specific comparisons fail closed because group-level evidence cannot be reclassified as HSBC UK proof."},
 "santander-uk": {"id":"BK-ENT-005","name":"Santander UK","scope":"UK bank within Santander group","period":"FY2024-Q1 2025","summary":"Evidence is available but narrower; branch/channel, cost and customer themes are visible with important unknowns.","themes":["Brand, channel and operating-model simplification","Cost transformation and productivity","Customer and digital engagement"],"evidence":"partial","unknowns":["Comparable evidence on digital engagement depth","Extent of UK-specific technology investment versus group platforms","Customer impact of channel and operating-model changes"],"changes":[("Channel and operating-model change is visible","Governed fixture evidence supports a bounded view of channel and simplification activity.","Commercially useful for questions on service model, inclusion and efficiency outcomes.","fact plus bounded interpretation"),("Productivity pressure is present","Cost and efficiency language appears in the current evidence period.","Raises timing questions around transformation investment and service outcomes.","fact"),("Digital evidence is not fully comparable","The package does not support parity with stronger peer evidence.","Prevents treating limited evidence as lack of activity.","safe limit")],"distinctive":"A narrower UK-specific evidence base makes channel and productivity questions more supportable than broad technology claims.","sector":"Digital engagement, cost productivity and resilience remain sector-consistent context.","tensions":["Brand simplification versus operational complexity","Cost reduction versus transformation investment"],"questions":["What customer outcomes are being used to judge channel and operating-model changes at Santander UK?","How are productivity priorities being balanced with transformation investment and resilience obligations?","Where does Santander UK rely on group platforms, and what evidence would show UK-specific technology change?","Which digital engagement measures are comparable with peers, and which are not currently evidenced?","What unresolved customer inclusion risks should be tested before interpreting channel migration as progress?"],"sources":["Human-curated deterministic fixture from public company reporting excerpts"],"safe":"Comparison of digital depth is safe-unavailable where comparable evidence is missing."},
}

SCOPE_LABELS={"enterprise-specific":"Specific to this bank","sector-wide":"Also visible across peers","sector-context":"Sector context only","unresolved":"Not enough evidence to compare"}

def audit_event(event_type:str, **payload):
    path=Path(__file__).resolve().parents[4]/"artifacts/flora-banking-audit.jsonl"; path.parent.mkdir(exist_ok=True)
    path.open("a",encoding="utf-8").write(json.dumps({"event_type":event_type,"lifecycle":"non_canonical_runtime_audit_event",**payload},sort_keys=True)+"\n")

def _lineage(bank): return stable_hash({"bank":bank["id"],"period":bank["period"],"sources":bank["sources"]})[:12]
def _ul(items): return "<ul>"+"".join(f"<li>{escape(i)}</li>" for i in items)+"</ul>"
def compact_evidence(bank): return f"Based mainly on recent company reporting and human-curated deterministic fixtures; suitable for understanding reported change, but not independent validation of realised outcomes. Evidence state: {escape(bank['evidence'])}."

def portfolio_page():
    audit_event("portfolio_opened", route="/flora/banking")
    cards="".join(f"<article class='card'><h2>{escape(b['name'])}</h2><p>{escape(b['summary'])}</p><p><strong>Enterprise Model:</strong> {escape(b['id'])}</p><p><strong>Themes:</strong> {escape(', '.join(b['themes'][:3]))}</p><p><strong>Material Unknowns:</strong> {len(b['unknowns'])}</p><p><strong>Evidence:</strong> {escape(b['evidence'])} · <strong>Latest period:</strong> {escape(b['period'])}</p><p><a class='primary-link' href='/flora/banking/{slug}'>Understand this bank</a> · <a href='/flora/banking/{slug}/evidence'>Inspect evidence</a></p><details><summary>Internal identity</summary><p>{escape(b['id'])} · lineage {_lineage(b)}</p></details></article>" for slug,b in BANKS.items())
    body=f"<section class='hero'><h1>UK Banking portfolio</h1><p>Bounded by governed portfolio Context Package CP-UK-BANKING-001. No ranking, scoring or recommendations.</p><p><a href='/flora/banking/compare'>Compare banks through common themes</a></p></section><section class='card'><h2>Portfolio synthesis</h2><p>Across UK Banking, the governed package shows digital engagement, balance-sheet economics, cost productivity, technology change and resilience/control moving together.</p><p><strong>Sector-wide:</strong> digital migration, cost productivity, regulation/control and resilience constraints.</p><p><strong>Distinctive movement:</strong> Lloyds shows a combined deposit-digital-technology package; Barclays shows simplification and capital discipline; NatWest combines customer franchise, deposits and simplification; HSBC UK and Santander UK include explicit evidence limits.</p><p><strong>Insufficient evidence:</strong> peer-comparable customer outcomes, UK-specific group-bank separation, realised transformation benefits and supplier dependency detail.</p></section><section class='grid'>{cards}</section>"
    return _page("UK Banking portfolio", body)

def bank_page(slug, briefing=False):
    b=BANKS.get(slug)
    if not b: return safe_unavailable_page("required enterprise identity is unresolved", slug),200
    audit_event("briefing_generated" if briefing else "bank_selected", bank=b["id"], route=f"/flora/banking/{slug}")
    changes="".join(f"<article><h3>{escape(t)}</h3><p>{escape(s)}</p><p><strong>Commercial significance:</strong> {escape(c)}</p><p><strong>Fact / interpretation:</strong> {escape(k)}</p><p><strong>Relevant Unknown:</strong> {escape(b['unknowns'][0])}</p><details><summary>Inspect evidence</summary><p>Lineage: {_lineage(b)}; sources: {escape(', '.join(b['sources']))}; period {escape(b['period'])}</p></details></article>" for t,s,c,k in b['changes'][:(3 if briefing else 5)])
    questions="".join(f"<article><p>{escape(q)}</p><details><summary>Originating Unknown or tension and Evidence</summary><p>Origin: {escape((b['unknowns']+b['tensions'])[i % (len(b['unknowns'])+len(b['tensions']))])}</p><p>Why now: current governed period {escape(b['period'])}; lineage {_lineage(b)}</p></details></article>" for i,q in enumerate(b['questions'][:(5 if briefing else 7)]))
    title=("Account preparation briefing — " if briefing else "")+b['name']
    body=f"<section class='hero'><h1>{escape(title)}</h1><p>Generated date: 2026-07-19 · Evidence period: {escape(b['period'])}</p><p><a href='/flora/banking/{slug}/briefing'>Account briefing</a> · <a href='/flora/banking/{slug}/evidence'>Inspect evidence</a> · <a href='/flora/banking/compare'>Compare banks</a></p></section><section class='card'><h2>Account in one minute</h2><p>{escape(b['summary'])}</p><p class='pill'>{escape(compact_evidence(b))}</p></section><section class='card'><h2>What has changed?</h2>{changes}</section><section class='card'><h2>Why it matters commercially</h2><p>{escape(b['distinctive'])}</p></section><section class='card'><h2>Why this bank now?</h2><p>{escape(b['name'])} merits closer commercial attention because governed changes are visible in {escape(', '.join(b['themes'][:3]))}, while material Unknowns remain unresolved. This is not a Recommendation.</p></section><section class='card'><h2>What appears distinctive</h2><p><strong>{SCOPE_LABELS['enterprise-specific']}:</strong> {escape(b['distinctive'])}</p></section><section class='card'><h2>What is also happening across the sector</h2><p><strong>{SCOPE_LABELS['sector-wide']}:</strong> {escape(b['sector'])}</p></section><section class='card'><h2>Strategic tensions</h2>{_ul(b['tensions'][:2])}<p>Each tension remains unresolved until further evidence is inspected.</p></section><section class='card'><h2>What remains unknown</h2>{_ul(b['unknowns'])}</section><section class='card'><h2>Questions worth exploring</h2>{questions}</section><section class='card'><h2>Evidence status</h2><p>{escape(compact_evidence(b))}</p></section>"
    return _page(title, body),200

def evidence_page(slug):
    b=BANKS.get(slug)
    if not b: return safe_unavailable_page("evidence is inaccessible because the bank identity is unresolved", slug),200
    audit_event("evidence_inspected", bank=b["id"])
    rows="".join(f"<tr><td>{escape(src)}</td><td>company-reported or human-supplied knowledge</td><td>{escape(b['period'])}</td><td>Lineage {_lineage(b)}</td></tr>" for src in b['sources'])
    return _page(f"Inspect evidence — {b['name']}", f"<section class='hero'><h1>Expanded evidence inspection</h1><p>{escape(b['name'])}</p></section><section class='card'><h2>Authority, freshness, corroboration, lineage and source passages</h2><table><tbody>{rows}</tbody></table><p>Detailed diagnostics remain behind Inspect evidence and collapsed by default in executive views.</p></section>"),200

def compare_page():
    audit_event("comparison_created", banks=','.join(b['id'] for b in BANKS.values()))
    rows=""
    for theme in THEMES:
        cells="".join(f"<td>{('enterprise-specific signal: '+escape(b['summary'])) if theme in b['themes'] else 'safe-unavailable: insufficient comparable evidence; this does not mean lack of activity'}<br><strong>Evidence period:</strong> {escape(b['period'])}<br><strong>Unknown:</strong> {escape(b['unknowns'][0])}<br><strong>Scope:</strong> {escape(SCOPE_LABELS['enterprise-specific'] if theme in b['themes'] else SCOPE_LABELS['unresolved'])}</td>" for b in BANKS.values())
        rows += f"<tr><th>{escape(theme)}</th>{cells}</tr>"
    body=f"<section class='hero'><h1>Five-bank theme comparison</h1><p>Governed peer comparison using common themes. No ordered priority, numeric assessment or comparative superiority language is used.</p></section><section class='card'><table><thead><tr><th>Theme</th>{''.join('<th>'+escape(b['name'])+'</th>' for b in BANKS.values())}</tr></thead><tbody>{rows}</tbody></table></section>"
    return _page("UK Banking comparison", body)

def safe_unavailable_page(reason, target):
    audit_event("safe_unavailable_returned", target=target, reason=reason)
    return _page("Safe unavailable", f"<section class='hero'><h1>Safe unavailable</h1><p>What cannot be concluded: a bounded banking briefing or comparison.</p><p>Why: {escape(reason)}.</p><p>Missing evidence: governed enterprise identity, comparable period, theme mapping and lineage.</p><p>What may still be inspected: available portfolio and evidence pages.</p></section>")
